name: Local

variables:
  - name: base_url
    value: http://localhost:8787
  - name: api_version
    value: v1
  - name: jwt_token
    value: ""
    secret: true
  - name: vinyl_id
    value: ""
  - name: track_id
    value: ""
  - name: filename
    value: ""
